[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "CRUDBuilder"
version = "0.0.1"
authors = [
  { name="Rich Winslow", email="Rich@tetricuslabs.com" },
    { name= "Leonard Mazzone", email="lenny@tetricuslabs.com"}
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]